### ISSUE TITLE
Update Extension on VS Marketplace

### ISSUE THREAD

**Issue by xxbc** [vscode-org-mode/vscode-org-mode#107]
Project Details

jsonreeder/vscode-org-mode
    No Pull Requests
    19 Open Issues
    **Last commit: 3 days ago**

Version | 0.5.0
**Last updated | 12/12/2017** 2:39:01 AM

**Comment by sipi** [comment]
:tada: Done, but I changed the publisher to reflect our new organization: https://marketplace.visualstudio.com/items?itemName=vscode-org-mode.org-mode

**Comment by GitMensch** [comment]
@sipi - Can someone unpublish the TooTone extension or at least add a fat note in the README "there" that it is superseded by this extension?
