### ISSUE TITLE
Coloring and theme

### ISSUE THREAD

**Issue by malekcellier** [vscode-org-mode/vscode-org-mode#123]
Hi

Thanks for making this extension.

I do not use the default vscode theme and as a result the keywords in the org file are not colored as they are shown in the pictures in the marketplace.

Is there a way to specify the colors for the keywords?

Thanks
Malek

**Comment by dmytrokyrychuk** [comment]
You can specify colors using `editor.tokenColorCustomizations` setting. See an example here: https://github.com/ajtoo/vscode-org-mode/pull/122#issuecomment-424277951
Use the `Developer: Inspect TM Scopes` command from the Command Palette in order to determine the scope of a symbol.
