### ISSUE TITLE
add meta data tag for orgmode

### ISSUE THREAD

**Issue by kenoyer130** [vscode-org-mode/vscode-org-mode#76]
If you search for orgmode in the Visual Code Extensions left panel nothing comes up. You have to search for org mode. I almost missed this great extension!

**Comment by bkidwell** [comment]
Org mode is stylized as "Org mode" on its [web site](http://orgmode.org/), and its project source control repository name is "org-mode".

But, it wouldn't hurt to add something to the the metadata for vscode-org-mode so that it matches a search in Extensions for "orgmode".

**Comment by mrkeuz** [comment]
+1 vote

**Comment by sipi** [comment]
DONE
Released on a new publisher to reflect our new organization: https://marketplace.visualstudio.com/items?itemName=vscode-org-mode.org-mode
