### ISSUE TITLE
how to fold and unfold levels ?

### ISSUE THREAD

**Issue by ghost** [vscode-org-mode/vscode-org-mode#85]
Sorry for the simple question but I didn't find a way to do this basic feature in this org mode...

**Comment by chaseadamsio** [comment]
currently there isn't a way to do that and as far as I know that's a VS Code limitation. They do folding based on the language specifying if its indention level or { } but there's not a way to define folding parameters uniquely per language.

**Comment by joevandyk** [comment]
Would that be something to bring up with the VS Code developers?

**Comment by cjay** [comment]
See https://github.com/Microsoft/vscode/issues/3422
This issue is relatively high up when sorting by upvotes.

**Comment by peon501** [comment]
@chaseadamsio { } folding dont work :)

if u have for example (in php):

function alala(){
$lalala = <<<SQL
aaaa
SQL;
$lalala = <<<SQL
aaaa
SQL;
$lalala = <<<SQL
aaaa
SQL;
$lalala = <<<SQL
aaaa
SQL;
}

and they cant fix it for ages.

**Comment by peon501** [comment]
![image](https://user-images.githubusercontent.com/1125765/35442545-501fe842-02b0-11e8-9c8d-1bce06f7851f.png)
soo functions looks like sh*t :D

**Comment by chaseadamsio** [comment]
@peon501 I don't know that this issue is the forum for the issue you're experiencing w/ folding, this is specifically for org-mode folding which is unrelated to PHP's SQL folding issue. If you'd like to get support for that, I'd recommend taking it to the PHP extension you've installed.

**Comment by rpeshkov** [comment]
Hope I'm not too late for the party. VSCode 1.21 has proposed extension API for [folding](https://code.visualstudio.com/updates/v1_21#_folding) that allows you to create custom folding providers. Currently I'm working on implementing folding in this extension and once I finish, I'll make PR. 

Notice that this PR should not be merged into main branch before this proposed API become stable because extensions that use proposed APIs are declined during publish.

**Comment by rpeshkov** [comment]
Made quick and dirty implementation of folding for the first level that demonstrates how will it look like in VSCode.

Screenshots:

![screen shot 2018-03-10 at 09 17 18](https://user-images.githubusercontent.com/701068/37239964-3b716212-2444-11e8-8dea-be05f566f25b.png)
![screen shot 2018-03-10 at 09 17 43](https://user-images.githubusercontent.com/701068/37239965-3b938932-2444-11e8-81e0-aaf62d7f057e.png)

**Comment by rpeshkov** [comment]
VSCode 1.22 released, but folding API is still in proposed status. Waiting for VSCode 1.23 :)

**Comment by rpeshkov** [comment]
Great news! In VSCode 1.23 folding provider API moved to official status! https://code.visualstudio.com/updates/v1_23#_folding-provider-api

Tomorrow I’ll be able to cleanup my PR and make update.

**Comment by xxbc** [comment]
merge this to master!

**Comment by LoveSponge** [comment]
Waking up this thread as it seems to have gone dead and the version i've downloaded from VS marketplace says 0.5.0, but when i download the 'Develop' branch as zip and drag it into the extentions directory, the version is 0.1.3, and folding still doesn't work.
help?

**Comment by salvadord** [comment]
I tried going back to version 0.1.3 but still no folding/unfolding. Any other suggestions??

**Comment by LoveSponge** [comment]
Hmm it worked for me, can you clarify that the version your vscode is looking at is correct & that the add on is running properly? Screenshot devtools if not.

When I realised there was an option to change it directly within vscode and roll back to an older version so easily it worked like a charm.

The last thing is just to check in your .vscode/extensions that it's actually the correct source

**Comment by salvadord** [comment]
The extension is working properly cause I can run other Org commands via the command palette. I also checked the .vscode/extensions and the org-mode version is v0.1.3.

When working, should I see 'Org: fold' and 'Org: unfold' commands (or similar) in the command palette?

thanks!

**Comment by LoveSponge** [comment]
No, the extension is more clever than that, it utilises vanilla vscode folding mechanisms, so you should be able to hover somewhere over the line numbers and see the folding icons like pull request #99.

You might have this hidden or disabled in your settings.

**Comment by salvadord** [comment]
ah is the vanilla vscode folding mechanism something built into vscode, or needs to be installed also as an extension? thx!

**Comment by LoveSponge** [comment]
Okay so it looks like downloading 0.1.3 isn't working properly on windows VSCode for some reason;
To get this working just download the (:DEVELOP) source as a ZIP from the repo and replace everything (delete it all) inside the .vscode/extensions folder in your user directory with the downloaded files. Open the directory with a terminal or NODEJS command prompt, run `npm i && tsc`

When it's done, close and re-open vscode and folding should be working.

**Comment by salvadord** [comment]
I downloaded the 'develop' branch code as zip and replaced the org-mode extension files in .vscode/extensions with these; then ran `npm i && tsc`. The extension is working, but still no code folding. I'm on a Mac OS 10.12.6 with Visual Studio Code 1.30.2

**Comment by sipi** [comment]
:tada: released, but the publisher was changed to reflect our new organization: https://marketplace.visualstudio.com/items?itemName=vscode-org-mode.org-mode
