### ISSUE TITLE
Update the changelog

### ISSUE THREAD

**Issue by ghisvail** [vscode-org-mode/vscode-org-mode#88]
The last version referenced in the [changelog](https://github.com/ajtoo/vscode-org-mode/blob/develop/CHANGELOG.md#013---2017-05-27) is version 0.1.3, whereas the package is at version 0.5. Please consider keeping the changelog up to date so changes to the package can be easily reviewed from the VSCode plugin manager.

**Comment by sipi** [comment]
It was an inconsistence between source version and marketplace version, the 0.1.3 is the 0.5 from the marketplace.
Notice new release on a different publisher to reflect the new organization: https://marketplace.visualstudio.com/items?itemName=vscode-org-mode.org-mode
